spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/loja
    username: loja
    password: lojaadmin
    driverClassName: org.postgresql.Driver

server:
  port: 8080
